#!/usr/bin/env bash
set -euo pipefail

repo_root="/opt/deepseek-harness/current"
deployment_root="$repo_root/deployments/trader-ops"
environment_file="/etc/deepseek-harness/trader-ops.env"
service_file="/etc/systemd/system/dsh-trader-ops.service"
action="${1:---enable}"

if [[ "$(id -u)" -ne 0 ]]; then
  printf 'Run this WeCom configuration as root through sudo.\n' >&2
  exit 1
fi
if [[ "$action" != --enable && "$action" != --disable ]]; then
  printf 'Usage: configure-wecom-runtime.sh [--enable|--disable]\n' >&2
  exit 1
fi
if [[ ! -f "$environment_file" || ! -f "$deployment_root/config/dsh/trader-ops-wecom.patch.yml" ]]; then
  printf 'Configure the base Trader Ops runtime before enabling WeCom.\n' >&2
  exit 1
fi

requested_bot_id="${WECOM_BOT_ID:-}"
requested_bot_secret="${WECOM_BOT_SECRET:-}"
requested_allowed_users="${WECOM_ALLOWED_USERS:-}"
requested_allowed_chats="${WECOM_ALLOWED_CHATS:-}"
requested_group_mode="${WECOM_GROUP_CONVERSATION_MODE:-}"
requested_wecom_sandbox="${TRADER_OPS_WECOM_SANDBOX:-}"

set -a
# This file is generated by the Trader Ops root configuration scripts.
# shellcheck source=/dev/null
source "$environment_file"
set +a

bot_id="${requested_bot_id:-${WECOM_BOT_ID:-}}"
bot_secret="${requested_bot_secret:-${WECOM_BOT_SECRET:-}}"
session_key="${WECOM_SESSION_KEY:-}"
allowed_users="${requested_allowed_users:-${WECOM_ALLOWED_USERS:-}}"
allowed_chats="${requested_allowed_chats:-${WECOM_ALLOWED_CHATS:-}}"
group_mode="${requested_group_mode:-${WECOM_GROUP_CONVERSATION_MODE:-shared}}"
wecom_sandbox="${requested_wecom_sandbox:-${TRADER_OPS_WECOM_SANDBOX:-read-only}}"

validate_atom() {
  local label="$1"
  local value="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9._@/-]+$ ]]; then
    printf '%s must contain only letters, digits, dot, underscore, @, slash, or hyphen.\n' "$label" >&2
    exit 1
  fi
}

validate_secret() {
  local label="$1"
  local value="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9._@/:+=-]+$ ]]; then
    printf '%s contains characters that cannot be stored safely in the systemd environment file.\n' "$label" >&2
    exit 1
  fi
}

validate_csv() {
  local label="$1"
  local value="$2"
  local required="$3"
  if [[ -z "$value" ]]; then
    if [[ "$required" == 1 ]]; then
      printf '%s must contain at least one exact id.\n' "$label" >&2
      exit 1
    fi
    return
  fi
  if [[ ",$value," == *",*,"* || ! "$value" =~ ^[A-Za-z0-9._@/-]+(,[A-Za-z0-9._@/-]+)*$ ]]; then
    printf '%s must be a comma-separated list of exact ids without spaces or wildcards.\n' "$label" >&2
    exit 1
  fi
}

if [[ "$action" == --enable ]]; then
  if [[ -z "$bot_id" ]]; then
    read -r -p 'Enter the enterprise WeCom BotID: ' bot_id
  fi
  if [[ -z "$bot_secret" ]]; then
    read -r -s -p 'Enter the enterprise WeCom bot secret: ' bot_secret
    printf '\n'
  fi
  if [[ -z "$allowed_users" ]]; then
    read -r -p 'Enter comma-separated allowed WeCom user ids: ' allowed_users
  fi
  if [[ -z "$requested_allowed_chats" && -z "${WECOM_ALLOWED_CHATS:-}" ]]; then
    read -r -p 'Enter comma-separated allowed WeCom group chat ids, or leave empty: ' allowed_chats
  fi
  if [[ -z "$session_key" ]]; then
    session_key="$(openssl rand -hex 32)"
  fi
  validate_atom WECOM_BOT_ID "$bot_id"
  validate_secret WECOM_BOT_SECRET "$bot_secret"
  validate_atom WECOM_SESSION_KEY "$session_key"
  validate_csv WECOM_ALLOWED_USERS "$allowed_users" 1
  validate_csv WECOM_ALLOWED_CHATS "$allowed_chats" 0
  if [[ "$group_mode" != shared && "$group_mode" != per-user ]]; then
    printf 'WECOM_GROUP_CONVERSATION_MODE must be shared or per-user.\n' >&2
    exit 1
  fi
  if [[ "$wecom_sandbox" != read-only && "$wecom_sandbox" != workspace-write ]]; then
    printf 'TRADER_OPS_WECOM_SANDBOX must be read-only or workspace-write.\n' >&2
    exit 1
  fi
  enabled=1
else
  enabled=0
fi

umask 077
original_environment="$(mktemp)"
next_environment="$(mktemp)"
committed=0
service_touched=0
cleanup() {
  local status=$?
  trap - EXIT
  if [[ "$status" -ne 0 && "$committed" == 0 ]]; then
    install -o root -g root -m 0600 "$original_environment" "$environment_file"
    if [[ "$service_touched" == 1 ]]; then
      systemctl reset-failed dsh-trader-ops >/dev/null 2>&1 || true
      systemctl restart dsh-trader-ops >/dev/null 2>&1 || true
    fi
    printf 'WeCom configuration failed; the previous Trader Ops environment was restored.\n' >&2
  fi
  rm -f -- "$original_environment" "$next_environment"
  exit "$status"
}
trap cleanup EXIT
install -m 0600 "$environment_file" "$original_environment"

while IFS= read -r line || [[ -n "$line" ]]; do
  case "$line" in
    TRADER_OPS_WECOM_ENABLED=*|TRADER_OPS_WECOM_SANDBOX=*|WECOM_BOT_ID=*|WECOM_BOT_SECRET=*|WECOM_SESSION_KEY=*|WECOM_ALLOWED_USERS=*|WECOM_ALLOWED_CHATS=*|WECOM_GROUP_CONVERSATION_MODE=*)
      ;;
    *)
      printf '%s\n' "$line" >>"$next_environment"
      ;;
  esac
done <"$environment_file"
cat >>"$next_environment" <<EOF
TRADER_OPS_WECOM_ENABLED=$enabled
TRADER_OPS_WECOM_SANDBOX=$wecom_sandbox
WECOM_BOT_ID=$bot_id
WECOM_BOT_SECRET=$bot_secret
WECOM_SESSION_KEY=$session_key
WECOM_ALLOWED_USERS=$allowed_users
WECOM_ALLOWED_CHATS=$allowed_chats
WECOM_GROUP_CONVERSATION_MODE=$group_mode
EOF
install -o root -g root -m 0600 "$next_environment" "$environment_file"

set -a
# shellcheck source=/dev/null
source "$environment_file"
set +a

if [[ "$enabled" == 1 ]]; then
  getent hosts openws.work.weixin.qq.com >/dev/null
  timeout 15 openssl s_client -connect openws.work.weixin.qq.com:443 \
    -servername openws.work.weixin.qq.com </dev/null 2>/dev/null \
    | grep -q 'Verify return code: 0'
fi

cd "$repo_root"
/usr/sbin/runuser --preserve-environment -u dsh -- env \
  CI=true HOME=/var/lib/deepseek-harness PATH=/usr/local/bin:/usr/bin:/bin \
  "$deployment_root/scripts/bootstrap-profile.sh"
/usr/sbin/runuser --preserve-environment -u dsh -- env \
  CI=true HOME=/var/lib/deepseek-harness PATH=/usr/local/bin:/usr/bin:/bin \
  "$deployment_root/scripts/verify-deployment.sh"

install -o root -g root -m 0644 \
  "$deployment_root/config/systemd/dsh-trader-ops.service" "$service_file"
systemctl daemon-reload
systemctl reset-failed dsh-trader-ops
service_touched=1
systemctl restart dsh-trader-ops

harness_ready() {
  local status
  status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
    http://127.0.0.1:3180/)" || return 1
  [[ "$status" == 200 || "$status" == 401 ]]
}

for _ in {1..60}; do
  if harness_ready && systemctl is-active --quiet dsh-trader-ops; then
    ready=1
    break
  fi
  sleep 1
done
if [[ "${ready:-0}" != 1 ]]; then
  printf 'Trader Ops did not become ready after applying the WeCom configuration.\n' >&2
  exit 1
fi
restart_count="$(systemctl show dsh-trader-ops --property=NRestarts --value)"
sleep 10
if ! harness_ready \
  || ! systemctl is-active --quiet dsh-trader-ops \
  || [[ "$(systemctl show dsh-trader-ops --property=NRestarts --value)" != "$restart_count" ]]; then
  printf 'Trader Ops did not remain stable after applying the WeCom configuration.\n' >&2
  exit 1
fi

committed=1
if [[ "$enabled" == 1 ]]; then
  printf 'Trader Ops WeCom long connection is enabled with exact user allowlisting.\n'
else
  printf 'Trader Ops WeCom long connection is disabled; stored credentials were retained.\n'
fi
